package ec

// api error code
const (
	SUCCESS = 0

	ERROR_HTTP                         = 1000
	ERROR_HTTP_REQUEST_CONTENTTYPE     = 1102 //requestHeader("Content-Type")
	ERROR_HTTP_REQUEST_CONTEXTBINDJSON = 1103
	ERROR_HTTP_REQUEST_JSONITEMNULL    = 1104
	ERROR_HTTP_REQUEST_URLPARAM        = 1105
	ERROR_HTTP_REQUEST_URLQUERYATOI    = 1100
	ERROR_HTTP_REQUEST_URLQUERYKEY     = 1101
	ERROR_HTTP_                        = 1111

	ERROR_DATABSE                    = 2000
	ERROR_DATABSE_QUERY              = 2101
	ERROR_DATABSE_QUERY_ITEMEXIST    = 2102
	ERROR_DATABSE_QUERY_ITEMNOTEXIST = 2103
	ERROR_DATABSE_INSERT             = 2104
	ERROR_DATABSE_UPDATE             = 2105
	ERROR_DATABSE_DELETE             = 2106
	ERROR_DATABSE_                   = 2222

	ERROR_SWITCH         = 3000
	ERROR_SWITCH_EXECUTE = 3100
	ERROR_SWITCH_        = 3333
)

// error message.
