package ec

// api error code
const (
	SUCCESS = 0

	ERROR_HTTP                         = 1000
	ERROR_HTTP_REQUEST_CONTENTTYPE     = 1001 //requestHeader("Content-Type")
	ERROR_HTTP_REQUEST_CONTEXTBINDJSON = 1002
	ERROR_HTTP_REQUEST_JSONITEMNULL    = 1003
	ERROR_HTTP_REQUEST_URLPARAM        = 1004
	ERROR_HTTP_REQUEST_URLQUERYATOI    = 1005
	ERROR_HTTP_REQUEST_URLQUERYKEY     = 1006
	ERROR_HTTP_                        = 1111

	ERROR_DATABSE                    = 2000
	ERROR_DATABSE_QUERY              = 2001
	ERROR_DATABSE_QUERY_ITEMEXIST    = 2002
	ERROR_DATABSE_QUERY_ITEMNOTEXIST = 2003
	ERROR_DATABSE_INSERT             = 2004
	ERROR_DATABSE_UPDATE             = 2005
	ERROR_DATABSE_DELETE             = 2006
	ERROR_DATABSE_                   = 2222

	ERROR_SWITCH                         = 3000
	ERROR_SWITCH_EXECUTE                 = 3001
	ERROR_SWITCH_EXECUTE_API             = 3002
	ERROR_SWITCH_EXECUTE_API_RESULT      = 3003
	ERROR_SWITCH_EXECUTE_BGAPI           = 3004
	ERROR_SWITCH_EXECUTE_BGAPI_ORIGINATE = 3005
	ERROR_SWITCH_EXECUTE_APP             = 3006
	ERROR_SWITCH_                        = 3333
)

// error message.
